### ISSUE TITLE
2022 Update?

### ISSUE THREAD

**Issue by Stephanie-Raymond** [OpenSourceActivismTech/us-zipcodes-congress#3]
Is a 2022 update available?

**Comment by jlev** [comment]
Hi Stephanie, this data is initially sourced from the US Census which doesn't provide intra-year updates.

There is another source from the HUD via USPS, but you will need to abide by their license agreement.
You can find those files at https://www.huduser.gov/portal/datasets/usps_crosswalk.html

**Comment by jlev** [comment]
Updated to the HUD Q4 2021 data, which is the most recent they've made available.
